openapi: 3.0.0
info:
  version: '1'
  title: MyLab.OidcFinisher
  description: 'Finish OpenID connect with Authorization Code Flow'
servers:
- url: http://base.addr/v1
paths: 

  '/oidc/token':
    
    post:
      summary: Provide OIDC tokens 
      tags:
        - OIDC
      parameters:
      - name: code
        description: Authorization code
        in: query
        schema: 
          type: string
        required: true
      - name: state
        description: State string
        in: query
        schema:
          type: string
        required: false
      - name: code_verifier
        description: Code verifier
        in: query
        schema:
          type: string
        required: false
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResult'
        403:
          description: Rejected
          
components:

  schemas:
  
    TokenResult:
      type: object
      description: Contains OIDC tokens
      properties:
        access_token: 
          type: string
          description: Access token
          example: '6c2fb58f2512498da42e88cffa397edd'
        refresh_token:
          type: string
          description: Refresh token
          example: '02141446ff36414387a5e14018185471'
        id_token:
          type: string
          description: ID token
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
        expires_in:
          type: integer
          example: 23000
          description: Expiration time of the Access Token in seconds since the response was generated