openapi: 3.0.0
info:
  version: '1'
  title: MyLab.OidcFinisher
  description: 'Finish OpenID connect with Authorization Code Flow'
servers:
- url: http://base.addr/v1
paths: 

  '/oidc/finish':
    
    post:
      summary: Finish OIDC 
      tags:
        - OIDC
      parameters:
      - name: code
        description: Authorization code
        in: query
        schema: 
          type: string
        required: true
      - name: state
        description: State string
        in: query
        schema:
          type: string
        required: false
      responses:
        200:
          description: Finished successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinishResult'
        403:
          description: Rejected
          
components:

  schemas:
  
    FinishResult:
      type: object
      description: Contains authentication process results
      properties:
        accessToken: 
          type: string
          description: Access token
          example: '6c2fb58f2512498da42e88cffa397edd'
        refreshToken:
          type: string
          description: Refresh token
          example: '02141446ff36414387a5e14018185471'
        idToken:
          type: string
          description: ID token
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'